name= input("Enter your name: ")
age= input ("Enter your age: ")
gender = input ("Enter your gender M/F: ")
weight = input ("Enter your weight in Kg: ")
print(name)
print(age)
print(gender)
print(weight)